baseURL = "https://chaire-design.fr"
languageCode = "en"
title = "Chaire design Jean Prouvé"
theme = "CDJP"
defaultContentLanguage = "fr"
ignoreErrors = ["error-disable-taxonomy"]

DefaultContentLanguage = "fr"
copyright = "chaire-design.fr"

[Params]
favicon = "icon.png"

[deployement]
order = [".webp", ".jpg$", ".gif$"]
  [deployment.targets]
  # An arbitrary name for this target.
  name = "CDJPdeploy"
  [deployment.matchers]
  # Set custom content type for /sitemap.xml 
  pattern = "^sitemap\\.xml$"
  contentType = "application/xml"
  gzip = true
  
[build]
  useResourceCacheWhen = "never"

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true
privacyEnhanced = true

[privacy.youtube]
disable = true
privacyEnhanced = true

[minify]
minifyOutput = true
merge = "deep"

[languages]
  [languages.fr]
    languageName = "FR"
    languageCode = "fr"
    weight = 1
  [languages.en]
    languageName = "EN"
    languageCode = "en"
    weight = 2
  [languages.jp]
    languageName = "JP"
    languageCode = "jp"
    weight = 3
